### ISSUE TITLE
vim integration setup issue

### ISSUE THREAD

**Issue by ga7g08** [devd/Academic-Writing-Check#12]
I followed your description of how to set up the vim integration, but ran into a small issue. The file `checkwriting.vim` needs to be modified: currently it points the syntax checker at [your build](https://github.com/devd/Academic-Writing-Check/blob/master/checkwriting.vim#L20). All the user needs to do is modify this to there installation directory. I don't know if your still maintaining this, but you should!

Personally it would have been enough to add another bullet point to the instructions telling people what to do. 

Cheers

**Comment by devd** [comment]
gaah !  facepalm. 

does https://github.com/devd/Academic-Writing-Check/commit/c2b00ed14285d24b51dfd9527be4b842ec954b99 look good to you?

**Comment by ga7g08** [comment]
Perfection! :)
